num1=input('enter first number')
num2=input('enter second number')
sum=float(num1)+float(num2)
min=float(num1)-float(num2)
mul=float(num1)*float(num2)
div=float(num1)/float(num2)
print('sum of {0}and{1} is {2}'.format(num1,num2,sum))
print('substraction of {0}and{1} is {2}'.format(num1,num2,min))
print('multiplication of {0}and{1} is {2}'.format(num1,num2,mul))
print('division of {0}and{1} is {2}'.format(num1,num2,div))